// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TC_Backend.Data;

#nullable disable

namespace TC_Backend.Migrations
{
    [DbContext(typeof(TC_BackendDbContext))]
    [Migration("20251113054552_Add tables for Simulation")]
    partial class AddtablesforSimulation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TC_Backend.Models.CompanyList", b =>
                {
                    b.Property<Guid>("ClId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClId");

                    b.HasIndex("TickerSymbol")
                        .IsUnique();

                    b.ToTable("CompanysList");
                });

            modelBuilder.Entity("TC_Backend.Models.CompanyProfile", b =>
                {
                    b.Property<Guid>("CPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CntEmployees")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CPId");

                    b.HasIndex("TickerSymbol")
                        .IsUnique();

                    b.ToTable("CompanyProfiles");
                });

            modelBuilder.Entity("TC_Backend.Models.FinancialReport", b =>
                {
                    b.Property<Guid>("FinancialReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BasicAverageShares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BasicEPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostOfRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DilutedAverageShares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DilutedEPS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DilutedNIAvailableToComStockholders")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EBIT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EBITDA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GrossProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetIncomeCommonStockholders")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetIncomeFromContinuingAndDiscontinuedOperation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetIncomeFromContinuingOperationNetMinorityInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetInterestIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetNonOperatingInterestIncomeExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NormalizedEBITDA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NormalizedIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OperatingExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OperatingIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherIncomeExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PretaxIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReconciledCostOfRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReconciledDepreciation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportLabel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TaxEffectOfUnusualItems")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxProvision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxRateForCalcs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TotalExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalOperatingIncomeAsReported")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalUnusualItems")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalUnusualItemsExcludingGoodwill")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FinancialReportId");

                    b.HasIndex("TickerSymbol");

                    b.ToTable("FinancialReports");
                });

            modelBuilder.Entity("TC_Backend.Models.GameModule", b =>
                {
                    b.Property<Guid>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredPoints")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("ModuleID");

                    b.HasIndex("RoleID");

                    b.ToTable("GameModules");
                });

            modelBuilder.Entity("TC_Backend.Models.GameSubModule", b =>
                {
                    b.Property<Guid>("SubModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSkippable")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModuleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("SubModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubModuleID");

                    b.HasIndex("ModuleID");

                    b.ToTable("GameSubModules");
                });

            modelBuilder.Entity("TC_Backend.Models.Holdings", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityOwned")
                        .HasColumnType("int");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PortfolioId");

                    b.HasIndex("TickerSymbol");

                    b.HasIndex("UserId", "TickerSymbol")
                        .IsUnique();

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("TC_Backend.Models.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecutedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderID");

                    b.HasIndex("TickerSymbol");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TC_Backend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int>("RequiredPoints")
                        .HasColumnType("int");

                    b.Property<int>("RoleLevel")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TC_Backend.Models.StockRecord", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AdjustedClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("RecordId");

                    b.HasIndex("TickerSymbol");

                    b.HasIndex("Date", "TickerSymbol")
                        .IsUnique();

                    b.ToTable("StockRecords");
                });

            modelBuilder.Entity("TC_Backend.Models.Trade", b =>
                {
                    b.Property<Guid>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SellerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TradeId");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("SellerUserId");

                    b.HasIndex("TickerSymbol");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("TC_Backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicturePublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleID");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_User_Username_validat", "Username NOT LIKE '%[^a-z0-9_]%'");
                        });
                });

            modelBuilder.Entity("TC_Backend.Models.UserFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FileId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserFiles");
                });

            modelBuilder.Entity("TC_Backend.Models.UserProgress", b =>
                {
                    b.Property<Guid>("ProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModuleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmoduleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProgressID");

                    b.HasIndex("ModuleID");

                    b.HasIndex("SubmoduleID");

                    b.HasIndex("UserID", "ModuleID", "SubmoduleID")
                        .IsUnique();

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("TC_Backend.Models.CompanyProfile", b =>
                {
                    b.HasOne("TC_Backend.Models.CompanyList", null)
                        .WithOne()
                        .HasForeignKey("TC_Backend.Models.CompanyProfile", "TickerSymbol")
                        .HasPrincipalKey("TC_Backend.Models.CompanyList", "TickerSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TC_Backend.Models.FinancialReport", b =>
                {
                    b.HasOne("TC_Backend.Models.CompanyList", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TC_Backend.Models.GameModule", b =>
                {
                    b.HasOne("TC_Backend.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TC_Backend.Models.GameSubModule", b =>
                {
                    b.HasOne("TC_Backend.Models.GameModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TC_Backend.Models.Holdings", b =>
                {
                    b.HasOne("TC_Backend.Models.CompanyList", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TC_Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TC_Backend.Models.Order", b =>
                {
                    b.HasOne("TC_Backend.Models.CompanyList", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TC_Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TC_Backend.Models.StockRecord", b =>
                {
                    b.HasOne("TC_Backend.Models.CompanyList", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TC_Backend.Models.Trade", b =>
                {
                    b.HasOne("TC_Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("BuyerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TC_Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TC_Backend.Models.CompanyList", null)
                        .WithMany()
                        .HasForeignKey("TickerSymbol")
                        .HasPrincipalKey("TickerSymbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TC_Backend.Models.User", b =>
                {
                    b.HasOne("TC_Backend.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TC_Backend.Models.UserFile", b =>
                {
                    b.HasOne("TC_Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TC_Backend.Models.UserProgress", b =>
                {
                    b.HasOne("TC_Backend.Models.GameModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TC_Backend.Models.GameSubModule", null)
                        .WithMany()
                        .HasForeignKey("SubmoduleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TC_Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
